### ISSUE TITLE
nonce too low happens when calling debug_traceBlockByNumber API

### ISSUE THREAD

**Issue by 0xburan** [XinFinOrg/XDPoSChain#256] opened 2023-04-26 14:49 UTC
Calling `debug_traceBlockByNumber` returns a "nonce too low" error.
This issue is easily reproduced by the following curl command.
I also run my own archive node and it return the same, which means this issue is a software one instead of a node dependant issue.
This error happens with some specific block.
I found blocks 0x2e0b6e0 and 0x2e0b6ee are so.

* Call erpc.xinfin.network
```
curl --location 'https://erpc.xinfin.network' \
--header 'Content-Type: application/json' \
--data '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "debug_traceBlockByNumber",
  "params": ["0x2e0b6e0"]
}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"nonce too low"}}
```

* Call erpc.xdcrpc.com
```
curl --location 'https://erpc.xdcrpc.com/' \
--header 'Content-Type: application/json' \
--data '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "debug_traceBlockByNumber",
  "params": ["0x2e0b6e0"] 
}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"nonce too low"}}
```

**Comment by gzliudan** [comment] 2023-04-27 04:01
I will look into this problem.

**Comment by sokiaoba** [comment] 2023-05-12 02:17
Hi, do you know when this issue will be fixed? @gzliudan

**Comment by gzliudan** [comment] 2023-05-12 02:20
This PR #260 should fix this problem. You can test it before merge.

**Comment by sokiaoba** [comment] 2023-05-12 02:23
@gzliudan Have you tested it?

**Comment by gzliudan** [comment] 2023-05-12 02:24
Yes.

**Comment by sokiaoba** [comment] 2023-05-12 02:25
Thanks. We'll try.

**Comment by wjrjerome** [comment] 2023-11-20 05:03
I would like to add my investigation while looking into another somewhat related issue reported by @gzliudan 
The issue was the nonce in transaction does not match what's inside the statsDB of the node. 
So for example, if you query below
```curl -s -X POST -H "Content-Type: application/json" https://erpc.apothem.network/ -d '
{
    "jsonrpc": "2.0",
    "id": 6200,
    "method": "eth_getBlockByNumber",
    "params":[
        "0x2e0b6e0", 
        true
    ]
}'
```
You will see for the address of `0xe65f06590ee4ed6d814309e5fa014b642b9272bd` it has nonce value of `0x8d45c` but for its second transaction, it still has the same nonce value within the same block. However, the third transaction does has the correct nonce value of `0x8d45d`

Looking into details, what i discovered is that the first transaction which has the to address of `"to": "0x0000000000000000000000000000000000000092",` is a special transaction within XDC node. They are so called "trading and lending transactions" and if you take a closer look of the code, **you will notice they were designed to NOT increment the nonce for each transaction on purpose**.
See these lines of code:
1. https://github.com/XinFinOrg/XDPoSChain/blob/master/core/state_processor.go#L222 (The `ApplyEmptyTransaction` method on purposely ignore the nonce incrementation)
2. https://github.com/XinFinOrg/XDPoSChain/blob/master/core/types/transaction.go#L39

So this is the reality that "some special transaction in XDC does not increment nonce" but you may ask why you see the "nonce too low" error? Here is why:
1. When you call any of the contract API or the debug APIs (including the debug_traceBlockByNumber), the transactions that were being pulled out has nonce NOT incremented (due to the above trading & lending reason). Code here: https://github.com/XinFinOrg/XDPoSChain/blob/master/eth/api_tracer.go#L406
4. However, when the method `ApplyMessages` was being called within this method, the nonce was being incremented in statsDB (See code https://github.com/XinFinOrg/XDPoSChain/blob/master/core/state_transition.go#L253)
5. What above code means is, when the first transaction is trading and has tx nonce of 1, by the time it finish the `ApplyMessages` method, the nonce for this address has been incremented to 2. When the second transaction from the same address comes in again into the `ApplyMessages` method, the transaction still says nonce of `1` (due to no nonce incrementation from trading lending tx) but the XDC stateDB already has nonce of 2. That's where the error "nonce too low" is coming from.

Dan's PR https://github.com/XinFinOrg/XDPoSChain/pull/260 has fixed the debug API so that we no longer see the errors, but however i believe this API response is now no longer true since it's not reflecting the actual nonce value inside the transaction (the API is returning the nonce value stored in statsDB). 

Hope you still following my above analysis so far. If i'm to summarise: **the root cause is that XDC has inconsistent value between what's inside the transaction and stats DB.** 
There are a few options on top of my head that I would like to hear feedback from:
Option 1: We do nothing, keep @gzliudan 's fix as it is and XDC accept the fact that nonce values are inconsistent
Option 2: We revert Dan's PR and apply this fix https://github.com/XinFinOrg/XDPoSChain/pull/362/files, but accept the fact that there are some special transactions (trading and lending) which won't increment the nonce.
Option 3: Completely re-wrote the logic in trading and lending so that the nonce is incremental in transaction. (This would be the best option as it follows eth standard and error prone for future development, however it come with huge development cost as i can see the trading system rely on not incrementing the nonce on purpose. This would be best fixed by the author of the trading and lending system guys)

fyi @fishermanymc @AnilChinchawale @liam-lai

**Closed as completed** 2024-03-19 09:42 UTC
